// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Archive struct { // archive (../../../:0:0)
	query *querybuilder.Selection

	id *ID
}

func (r *Archive) WithGraphQLQuery(q *querybuilder.Selection) *Archive {
	return &Archive{
		query: q,
	}
}

// A unique identifier for this Archive.
func (r *Archive) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Archive) XXX_GraphQLType() string {
	return "Archive"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Archive) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Archive) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Archive) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Archive) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Archive{query: selectNode(dag.query, id, "Archive")}
	return nil
}

// ArchiveTarOpts contains options for Archive.Tar
type ArchiveTarOpts struct {
	Gzip bool
}

func (r *Archive) Tar(directory *Directory, opts ...ArchiveTarOpts) *File {
	assertNotNil("directory", directory)
	q := r.query.Select("tar")
	for i := len(opts) - 1; i >= 0; i-- {
		// `gzip` optional argument
		if !querybuilder.IsZeroValue(opts[i].Gzip) {
			q = q.Arg("gzip", opts[i].Gzip)
		}
	}
	q = q.Arg("directory", directory)

	return &File{
		query: q,
	}
}

func (r *Archive) Untar(file *File) *Directory {
	assertNotNil("file", file)
	q := r.query.Select("untar")
	q = q.Arg("file", file)

	return &Directory{
		query: q,
	}
}

func (r *Archive) Zip(directory *Directory) *File {
	assertNotNil("directory", directory)
	q := r.query.Select("zip")
	q = q.Arg("directory", directory)

	return &File{
		query: q,
	}
}

// ArchiveOpts contains options for Query.Archive
type ArchiveOpts struct {
	Container *Container
}

func (r *Query) Archive(opts ...ArchiveOpts) *Archive { // archive (../../../:0:0)
	q := r.query.Select("archive")
	for i := len(opts) - 1; i >= 0; i-- {
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Archive{
		query: q,
	}
}
