// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Mise struct { // mise (../../../:0:0)
	query *querybuilder.Selection

	doctor *Void
	id     *ID
}

func (r *Mise) WithGraphQLQuery(q *querybuilder.Selection) *Mise {
	return &Mise{
		query: q,
	}
}

// MiseContainerOpts contains options for Mise.Container
type MiseContainerOpts struct {
	NoEnv bool

	NoHooks bool

	Tools []string
}

func (r *Mise) Container(opts ...MiseContainerOpts) *Container {
	q := r.query.Select("container")
	for i := len(opts) - 1; i >= 0; i-- {
		// `noEnv` optional argument
		if !querybuilder.IsZeroValue(opts[i].NoEnv) {
			q = q.Arg("noEnv", opts[i].NoEnv)
		}
		// `noHooks` optional argument
		if !querybuilder.IsZeroValue(opts[i].NoHooks) {
			q = q.Arg("noHooks", opts[i].NoHooks)
		}
		// `tools` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tools) {
			q = q.Arg("tools", opts[i].Tools)
		}
	}

	return &Container{
		query: q,
	}
}

// MiseDoctorOpts contains options for Mise.Doctor
type MiseDoctorOpts struct {
	NoEnv bool

	NoHooks bool

	Tools []string

	Container *Container
}

func (r *Mise) Doctor(ctx context.Context, opts ...MiseDoctorOpts) error {
	if r.doctor != nil {
		return nil
	}
	q := r.query.Select("doctor")
	for i := len(opts) - 1; i >= 0; i-- {
		// `noEnv` optional argument
		if !querybuilder.IsZeroValue(opts[i].NoEnv) {
			q = q.Arg("noEnv", opts[i].NoEnv)
		}
		// `noHooks` optional argument
		if !querybuilder.IsZeroValue(opts[i].NoHooks) {
			q = q.Arg("noHooks", opts[i].NoHooks)
		}
		// `tools` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tools) {
			q = q.Arg("tools", opts[i].Tools)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return q.Execute(ctx)
}

// A unique identifier for this Mise.
func (r *Mise) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Mise) XXX_GraphQLType() string {
	return "Mise"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Mise) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Mise) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Mise) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Mise) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Mise{query: selectNode(dag.query, id, "Mise")}
	return nil
}

// MiseOpts contains options for Query.Mise
type MiseOpts struct {

	// Default: "."
	Path string

	// Default: "2026.5.15"
	Version string
}

func (r *Query) Mise(ws *Workspace, opts ...MiseOpts) *Mise { // mise (../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("mise")
	for i := len(opts) - 1; i >= 0; i-- {
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}
	q = q.Arg("ws", ws)

	return &Mise{
		query: q,
	}
}
