// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"github.com/logsquaredn/rubber/.dagger/modules/gh/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Gh) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Container *dagger.Container
	}
	concrete.Container = r.Container
	return json.Marshal(&concrete)
}

func (r *Gh) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Container *dagger.Container
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Container = concrete.Container
	return nil
}

func (r Release) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Gh   *Gh
		Repo string
		Tag  string
	}
	concrete.Gh = r.Gh
	concrete.Repo = r.Repo
	concrete.Tag = r.Tag
	return json.Marshal(&concrete)
}

func (r *Release) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Gh   *Gh
		Repo string
		Tag  string
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Gh = concrete.Gh
	r.Repo = concrete.Repo
	r.Tag = concrete.Tag
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Gh":
		switch fnName {
		case "Release":
			var parent Gh
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var repo string
			if inputArgs["repo"] != nil {
				err = json.Unmarshal([]byte(inputArgs["repo"]), &repo)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg repo", err))
				}
			}
			var tag string
			if inputArgs["tag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tag"]), &tag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tag", err))
				}
			}
			return (*Gh).Release(&parent, repo, tag), nil
		case "SetSecret":
			var parent Gh
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var name string
			if inputArgs["name"] != nil {
				err = json.Unmarshal([]byte(inputArgs["name"]), &name)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg name", err))
				}
			}
			var body *dagger.Secret
			if inputArgs["body"] != nil {
				err = json.Unmarshal([]byte(inputArgs["body"]), &body)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg body", err))
				}
			}
			var app string
			if inputArgs["app"] != nil {
				err = json.Unmarshal([]byte(inputArgs["app"]), &app)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg app", err))
				}
			}
			var env string
			if inputArgs["env"] != nil {
				err = json.Unmarshal([]byte(inputArgs["env"]), &env)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg env", err))
				}
			}
			var org string
			if inputArgs["org"] != nil {
				err = json.Unmarshal([]byte(inputArgs["org"]), &org)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg org", err))
				}
			}
			var visibility string
			if inputArgs["visibility"] != nil {
				err = json.Unmarshal([]byte(inputArgs["visibility"]), &visibility)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg visibility", err))
				}
			}
			var user bool
			if inputArgs["user"] != nil {
				err = json.Unmarshal([]byte(inputArgs["user"]), &user)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg user", err))
				}
			}
			var noReposSelected bool
			if inputArgs["noReposSelected"] != nil {
				err = json.Unmarshal([]byte(inputArgs["noReposSelected"]), &noReposSelected)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg noReposSelected", err))
				}
			}
			var repo []string
			if inputArgs["repo"] != nil {
				err = json.Unmarshal([]byte(inputArgs["repo"]), &repo)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg repo", err))
				}
			}
			return nil, (*Gh).SetSecret(&parent, ctx, name, body, app, env, org, visibility, user, noReposSelected, repo)
		case "SetVariable":
			var parent Gh
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var name string
			if inputArgs["name"] != nil {
				err = json.Unmarshal([]byte(inputArgs["name"]), &name)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg name", err))
				}
			}
			var body *dagger.Secret
			if inputArgs["body"] != nil {
				err = json.Unmarshal([]byte(inputArgs["body"]), &body)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg body", err))
				}
			}
			var env string
			if inputArgs["env"] != nil {
				err = json.Unmarshal([]byte(inputArgs["env"]), &env)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg env", err))
				}
			}
			var org string
			if inputArgs["org"] != nil {
				err = json.Unmarshal([]byte(inputArgs["org"]), &org)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg org", err))
				}
			}
			var visibility string
			if inputArgs["visibility"] != nil {
				err = json.Unmarshal([]byte(inputArgs["visibility"]), &visibility)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg visibility", err))
				}
			}
			var repo []string
			if inputArgs["repo"] != nil {
				err = json.Unmarshal([]byte(inputArgs["repo"]), &repo)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg repo", err))
				}
			}
			return nil, (*Gh).SetVariable(&parent, ctx, name, body, env, org, visibility, repo)
		case "":
			var parent Gh
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var githubToken *dagger.Secret
			if inputArgs["githubToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["githubToken"]), &githubToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg githubToken", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return New(githubToken, container), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Release":
		switch fnName {
		case "Create":
			var parent Release
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var title string
			if inputArgs["title"] != nil {
				err = json.Unmarshal([]byte(inputArgs["title"]), &title)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg title", err))
				}
			}
			var generateNotes bool
			if inputArgs["generateNotes"] != nil {
				err = json.Unmarshal([]byte(inputArgs["generateNotes"]), &generateNotes)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg generateNotes", err))
				}
			}
			var latest bool
			if inputArgs["latest"] != nil {
				err = json.Unmarshal([]byte(inputArgs["latest"]), &latest)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg latest", err))
				}
			}
			var prerelease bool
			if inputArgs["prerelease"] != nil {
				err = json.Unmarshal([]byte(inputArgs["prerelease"]), &prerelease)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg prerelease", err))
				}
			}
			var draft bool
			if inputArgs["draft"] != nil {
				err = json.Unmarshal([]byte(inputArgs["draft"]), &draft)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg draft", err))
				}
			}
			var verifyTag bool
			if inputArgs["verifyTag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["verifyTag"]), &verifyTag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg verifyTag", err))
				}
			}
			return nil, (*Release).Create(&parent, ctx, title, generateNotes, latest, prerelease, draft, verifyTag)
		case "Edit":
			var parent Release
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var title string
			if inputArgs["title"] != nil {
				err = json.Unmarshal([]byte(inputArgs["title"]), &title)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg title", err))
				}
			}
			var generateNotes bool
			if inputArgs["generateNotes"] != nil {
				err = json.Unmarshal([]byte(inputArgs["generateNotes"]), &generateNotes)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg generateNotes", err))
				}
			}
			var latest bool
			if inputArgs["latest"] != nil {
				err = json.Unmarshal([]byte(inputArgs["latest"]), &latest)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg latest", err))
				}
			}
			var prerelease bool
			if inputArgs["prerelease"] != nil {
				err = json.Unmarshal([]byte(inputArgs["prerelease"]), &prerelease)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg prerelease", err))
				}
			}
			var draft bool
			if inputArgs["draft"] != nil {
				err = json.Unmarshal([]byte(inputArgs["draft"]), &draft)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg draft", err))
				}
			}
			var verifyTag bool
			if inputArgs["verifyTag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["verifyTag"]), &verifyTag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg verifyTag", err))
				}
			}
			return nil, (*Release).Edit(&parent, ctx, title, generateNotes, latest, prerelease, draft, verifyTag)
		case "Upload":
			var parent Release
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var assets []*dagger.File
			if inputArgs["assets"] != nil {
				err = json.Unmarshal([]byte(inputArgs["assets"]), &assets)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg assets", err))
				}
			}
			var clobber bool
			if inputArgs["clobber"] != nil {
				err = json.Unmarshal([]byte(inputArgs["clobber"]), &clobber)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg clobber", err))
				}
			}
			return nil, (*Release).Upload(&parent, ctx, assets, clobber)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithObject(
				dag.TypeDef().WithObject("Gh", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 10, 6)}).
					WithFunction(
						dag.Function("Release",
							dag.TypeDef().WithObject("Release")).
							WithSourceMap(dag.SourceMap("main.go", 39, 1)).
							WithArg("repo", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 39, 22)}).
							WithArg("tag", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 39, 28)})).
					WithFunction(
						dag.Function("SetSecret",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithSourceMap(dag.SourceMap("main.go", 177, 1)).
							WithArg("name", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 179, 2)}).
							WithArg("body", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 180, 2)}).
							WithArg("app", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 182, 2)}).
							WithArg("env", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 184, 2)}).
							WithArg("org", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 186, 2)}).
							WithArg("visibility", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 188, 2)}).
							WithArg("user", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 190, 2)}).
							WithArg("noReposSelected", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 192, 2)}).
							WithArg("repo", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 194, 2)})).
					WithFunction(
						dag.Function("SetVariable",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithSourceMap(dag.SourceMap("main.go", 199, 1)).
							WithArg("name", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 201, 2)}).
							WithArg("body", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 202, 2)}).
							WithArg("env", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 204, 2)}).
							WithArg("org", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 206, 2)}).
							WithArg("visibility", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 208, 2)}).
							WithArg("repo", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 210, 2)})).
					WithField("Container", dag.TypeDef().WithObject("Container"), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("main.go", 11, 2)}).
					WithConstructor(
						dag.Function("New",
							dag.TypeDef().WithObject("Gh")).
							WithSourceMap(dag.SourceMap("main.go", 14, 1)).
							WithArg("githubToken", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 15, 2)}).
							WithArg("container", dag.TypeDef().WithObject("Container").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 17, 2)}))).
			WithObject(
				dag.TypeDef().WithObject("Release", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 30, 6)}).
					WithFunction(
						dag.Function("Create",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithSourceMap(dag.SourceMap("main.go", 43, 1)).
							WithArg("title", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 46, 2)}).
							WithArg("generateNotes", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 48, 2)}).
							WithArg("latest", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 50, 2)}).
							WithArg("prerelease", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 52, 2)}).
							WithArg("draft", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 54, 2)}).
							WithArg("verifyTag", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 56, 2)})).
					WithFunction(
						dag.Function("Edit",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithSourceMap(dag.SourceMap("main.go", 87, 1)).
							WithArg("title", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 90, 2)}).
							WithArg("generateNotes", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 92, 2)}).
							WithArg("latest", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 94, 2)}).
							WithArg("prerelease", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 96, 2)}).
							WithArg("draft", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 98, 2)}).
							WithArg("verifyTag", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 100, 2)})).
					WithFunction(
						dag.Function("Upload",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithSourceMap(dag.SourceMap("main.go", 131, 1)).
							WithArg("assets", dag.TypeDef().WithListOf(dag.TypeDef().WithObject("File")), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 133, 2)}).
							WithArg("clobber", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 135, 2)}))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
