// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Go struct { // go (../../../:0:0)
	query *querybuilder.Selection

	id          *ID
	staticcheck *Void
	test        *Void
	vet         *Void
	vulncheck   *Void
}

func (r *Go) WithGraphQLQuery(q *querybuilder.Selection) *Go {
	return &Go{
		query: q,
	}
}

// GoBuildOpts contains options for Go.Build
type GoBuildOpts struct {

	// Default: "./"
	Pkg string

	// Default: "-s -w"
	Ldflags string

	Cgo bool

	Goarch string

	Goos string
}

func (r *Go) Build(opts ...GoBuildOpts) *File {
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `ldflags` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ldflags) {
			q = q.Arg("ldflags", opts[i].Ldflags)
		}
		// `cgo` optional argument
		if !querybuilder.IsZeroValue(opts[i].Cgo) {
			q = q.Arg("cgo", opts[i].Cgo)
		}
		// `goarch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goarch) {
			q = q.Arg("goarch", opts[i].Goarch)
		}
		// `goos` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goos) {
			q = q.Arg("goos", opts[i].Goos)
		}
	}

	return &File{
		query: q,
	}
}

func (r *Go) Container() *Container {
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// GoFmtOpts contains options for Go.Fmt
type GoFmtOpts struct {

	// Default: "./..."
	Pkg string
}

func (r *Go) Fmt(opts ...GoFmtOpts) *Changeset {
	q := r.query.Select("fmt")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
	}

	return &Changeset{
		query: q,
	}
}

// GoGenerateOpts contains options for Go.Generate
type GoGenerateOpts struct {

	// Default: "./..."
	Pkg string
}

func (r *Go) Generate(opts ...GoGenerateOpts) *Changeset {
	q := r.query.Select("generate")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
	}

	return &Changeset{
		query: q,
	}
}

// A unique identifier for this Go.
func (r *Go) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Go) XXX_GraphQLType() string {
	return "Go"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Go) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Go) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Go) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Go) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Go{query: selectNode(dag.query, id, "Go")}
	return nil
}

// GoStaticcheckOpts contains options for Go.Staticcheck
type GoStaticcheckOpts struct {

	// Default: "./..."
	Pkg string

	// Default: "latest"
	Version string
}

func (r *Go) Staticcheck(ctx context.Context, opts ...GoStaticcheckOpts) error {
	if r.staticcheck != nil {
		return nil
	}
	q := r.query.Select("staticcheck")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return q.Execute(ctx)
}

// GoTestOpts contains options for Go.Test
type GoTestOpts struct {

	// Default: "."
	Path string

	// Default: "./..."
	Pkg string

	Race bool

	Cgo bool

	Tags []string
}

func (r *Go) Test(ctx context.Context, workspace *Workspace, opts ...GoTestOpts) error {
	assertNotNil("workspace", workspace)
	if r.test != nil {
		return nil
	}
	q := r.query.Select("test")
	for i := len(opts) - 1; i >= 0; i-- {
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `race` optional argument
		if !querybuilder.IsZeroValue(opts[i].Race) {
			q = q.Arg("race", opts[i].Race)
		}
		// `cgo` optional argument
		if !querybuilder.IsZeroValue(opts[i].Cgo) {
			q = q.Arg("cgo", opts[i].Cgo)
		}
		// `tags` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tags) {
			q = q.Arg("tags", opts[i].Tags)
		}
	}
	q = q.Arg("workspace", workspace)

	return q.Execute(ctx)
}

// GoTidyOpts contains options for Go.Tidy
type GoTidyOpts struct {

	// Default: "."
	Path string
}

func (r *Go) Tidy(workspace *Workspace, opts ...GoTidyOpts) *Changeset {
	assertNotNil("workspace", workspace)
	q := r.query.Select("tidy")
	for i := len(opts) - 1; i >= 0; i-- {
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
	}
	q = q.Arg("workspace", workspace)

	return &Changeset{
		query: q,
	}
}

// GoVetOpts contains options for Go.Vet
type GoVetOpts struct {

	// Default: "./..."
	Pkg string
}

func (r *Go) Vet(ctx context.Context, opts ...GoVetOpts) error {
	if r.vet != nil {
		return nil
	}
	q := r.query.Select("vet")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
	}

	return q.Execute(ctx)
}

// GoVulncheckOpts contains options for Go.Vulncheck
type GoVulncheckOpts struct {

	// Default: "./..."
	Pkg string

	// Default: "latest"
	Version string
}

func (r *Go) Vulncheck(ctx context.Context, opts ...GoVulncheckOpts) error {
	if r.vulncheck != nil {
		return nil
	}
	q := r.query.Select("vulncheck")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return q.Execute(ctx)
}

// GoOpts contains options for Query.Go
type GoOpts struct {

	// Default: "."
	Path string

	Container *Container
}

func (r *Query) Go(workspace *Workspace, opts ...GoOpts) *Go { // go (../../../:0:0)
	assertNotNil("workspace", workspace)
	q := r.query.Select("go")
	for i := len(opts) - 1; i >= 0; i-- {
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}
	q = q.Arg("workspace", workspace)

	return &Go{
		query: q,
	}
}
