name = "mise"
engineVersion = "v0.21.7"

[runtime]
  source = "go"

[[dependencies]]
  name = "arch"
  source = "../arch"

[[dependencies]]
  name = "archive"
  source = "../archive"

[[dependencies]]
  name = "wolfi"
  source = "github.com/dagger/dagger/modules/wolfi@v0.21.7"
  pin = "054f94b2d86c0ac00bef11ac4550816973c4aeef"
