// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"github.com/logsquaredn/rubber/.dagger/modules/godot/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Godot) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Container       *dagger.Container
		ExportTemplates *dagger.Directory
		Version         string
		Flavor          string
	}
	concrete.Container = r.Container
	concrete.ExportTemplates = r.ExportTemplates
	concrete.Version = r.Version
	concrete.Flavor = r.Flavor
	return json.Marshal(&concrete)
}

func (r *Godot) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Container       *dagger.Container
		ExportTemplates *dagger.Directory
		Version         string
		Flavor          string
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Container = concrete.Container
	r.ExportTemplates = concrete.ExportTemplates
	r.Version = concrete.Version
	r.Flavor = concrete.Flavor
	return nil
}

func (r Export) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Pck    *dagger.File
		Binary *dagger.File
	}
	concrete.Pck = r.Pck
	concrete.Binary = r.Binary
	return json.Marshal(&concrete)
}

func (r *Export) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Pck    *dagger.File
		Binary *dagger.File
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Pck = concrete.Pck
	r.Binary = concrete.Binary
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Godot":
		switch fnName {
		case "ExportDebug":
			var parent Godot
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var workspace *dagger.Workspace
			if inputArgs["workspace"] != nil {
				err = json.Unmarshal([]byte(inputArgs["workspace"]), &workspace)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg workspace", err))
				}
			}
			var preset string
			if inputArgs["preset"] != nil {
				err = json.Unmarshal([]byte(inputArgs["preset"]), &preset)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg preset", err))
				}
			}
			var path string
			if inputArgs["path"] != nil {
				err = json.Unmarshal([]byte(inputArgs["path"]), &path)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg path", err))
				}
			}
			var osslsigncodeVersion string
			if inputArgs["osslsigncodeVersion"] != nil {
				err = json.Unmarshal([]byte(inputArgs["osslsigncodeVersion"]), &osslsigncodeVersion)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg osslsigncodeVersion", err))
				}
			}
			var scriptEncryptionKey *dagger.Secret
			if inputArgs["scriptEncryptionKey"] != nil {
				err = json.Unmarshal([]byte(inputArgs["scriptEncryptionKey"]), &scriptEncryptionKey)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg scriptEncryptionKey", err))
				}
			}
			var windowsCodesignIdentityType string
			if inputArgs["windowsCodesignIdentityType"] != nil {
				err = json.Unmarshal([]byte(inputArgs["windowsCodesignIdentityType"]), &windowsCodesignIdentityType)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg windowsCodesignIdentityType", err))
				}
			}
			var windowsCodesignIdentity *dagger.File
			if inputArgs["windowsCodesignIdentity"] != nil {
				err = json.Unmarshal([]byte(inputArgs["windowsCodesignIdentity"]), &windowsCodesignIdentity)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg windowsCodesignIdentity", err))
				}
			}
			var windowsCodesignPassword *dagger.Secret
			if inputArgs["windowsCodesignPassword"] != nil {
				err = json.Unmarshal([]byte(inputArgs["windowsCodesignPassword"]), &windowsCodesignPassword)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg windowsCodesignPassword", err))
				}
			}
			return (*Godot).ExportDebug(&parent, ctx, workspace, preset, path, osslsigncodeVersion, scriptEncryptionKey, windowsCodesignIdentityType, windowsCodesignIdentity, windowsCodesignPassword)
		case "ExportRelease":
			var parent Godot
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var workspace *dagger.Workspace
			if inputArgs["workspace"] != nil {
				err = json.Unmarshal([]byte(inputArgs["workspace"]), &workspace)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg workspace", err))
				}
			}
			var preset string
			if inputArgs["preset"] != nil {
				err = json.Unmarshal([]byte(inputArgs["preset"]), &preset)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg preset", err))
				}
			}
			var path string
			if inputArgs["path"] != nil {
				err = json.Unmarshal([]byte(inputArgs["path"]), &path)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg path", err))
				}
			}
			var osslsigncodeVersion string
			if inputArgs["osslsigncodeVersion"] != nil {
				err = json.Unmarshal([]byte(inputArgs["osslsigncodeVersion"]), &osslsigncodeVersion)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg osslsigncodeVersion", err))
				}
			}
			var scriptEncryptionKey *dagger.Secret
			if inputArgs["scriptEncryptionKey"] != nil {
				err = json.Unmarshal([]byte(inputArgs["scriptEncryptionKey"]), &scriptEncryptionKey)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg scriptEncryptionKey", err))
				}
			}
			var windowsCodesignIdentityType string
			if inputArgs["windowsCodesignIdentityType"] != nil {
				err = json.Unmarshal([]byte(inputArgs["windowsCodesignIdentityType"]), &windowsCodesignIdentityType)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg windowsCodesignIdentityType", err))
				}
			}
			var windowsCodesignIdentity *dagger.File
			if inputArgs["windowsCodesignIdentity"] != nil {
				err = json.Unmarshal([]byte(inputArgs["windowsCodesignIdentity"]), &windowsCodesignIdentity)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg windowsCodesignIdentity", err))
				}
			}
			var windowsCodesignPassword *dagger.Secret
			if inputArgs["windowsCodesignPassword"] != nil {
				err = json.Unmarshal([]byte(inputArgs["windowsCodesignPassword"]), &windowsCodesignPassword)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg windowsCodesignPassword", err))
				}
			}
			return (*Godot).ExportRelease(&parent, ctx, workspace, preset, path, osslsigncodeVersion, scriptEncryptionKey, windowsCodesignIdentityType, windowsCodesignIdentity, windowsCodesignPassword)
		case "":
			var parent Godot
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var version string
			if inputArgs["version"] != nil {
				err = json.Unmarshal([]byte(inputArgs["version"]), &version)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg version", err))
				}
			}
			var flavor string
			if inputArgs["flavor"] != nil {
				err = json.Unmarshal([]byte(inputArgs["flavor"]), &flavor)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg flavor", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return New(ctx, version, flavor, container)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithObject(
				dag.TypeDef().WithObject("Godot", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 20, 6)}).
					WithFunction(
						dag.Function("ExportDebug",
							dag.TypeDef().WithObject("Export")).
							WithSourceMap(dag.SourceMap("main.go", 177, 1)).
							WithArg("workspace", dag.TypeDef().WithObject("Workspace"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 179, 2)}).
							WithArg("preset", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 180, 2)}).
							WithArg("path", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 181, 2)}).
							WithArg("osslsigncodeVersion", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 183, 2)}).
							WithArg("scriptEncryptionKey", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 185, 2)}).
							WithArg("windowsCodesignIdentityType", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 187, 2)}).
							WithArg("windowsCodesignIdentity", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 189, 2)}).
							WithArg("windowsCodesignPassword", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 191, 2)})).
					WithFunction(
						dag.Function("ExportRelease",
							dag.TypeDef().WithObject("Export")).
							WithSourceMap(dag.SourceMap("main.go", 158, 1)).
							WithArg("workspace", dag.TypeDef().WithObject("Workspace"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 160, 2)}).
							WithArg("preset", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 161, 2)}).
							WithArg("path", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 162, 2)}).
							WithArg("osslsigncodeVersion", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 164, 2)}).
							WithArg("scriptEncryptionKey", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 166, 2)}).
							WithArg("windowsCodesignIdentityType", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 168, 2)}).
							WithArg("windowsCodesignIdentity", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 170, 2)}).
							WithArg("windowsCodesignPassword", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 172, 2)})).
					WithField("Container", dag.TypeDef().WithObject("Container"), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("main.go", 21, 2)}).
					WithField("ExportTemplates", dag.TypeDef().WithObject("Directory"), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("main.go", 22, 2)}).
					WithConstructor(
						dag.Function("New",
							dag.TypeDef().WithObject("Godot")).
							WithSourceMap(dag.SourceMap("main.go", 29, 1)).
							WithArg("version", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 33, 2), DefaultValue: dagger.JSON("\"4.6.1\"")}).
							WithArg("flavor", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 36, 2), DefaultValue: dagger.JSON("\"stable\"")}).
							WithArg("container", dag.TypeDef().WithObject("Container").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 38, 2)}))).
			WithObject(
				dag.TypeDef().WithObject("Export", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 153, 6)}).
					WithField("Pck", dag.TypeDef().WithObject("File"), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("main.go", 154, 2)}).
					WithField("Binary", dag.TypeDef().WithObject("File"), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("main.go", 155, 2)})), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
