// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type ControllerGen struct { // controller-gen (../../../:0:0)
	query *querybuilder.Selection

	id *ID
}

func (r *ControllerGen) WithGraphQLQuery(q *querybuilder.Selection) *ControllerGen {
	return &ControllerGen{
		query: q,
	}
}

func (r *ControllerGen) Container() *Container {
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// ControllerGenCrdOpts contains options for ControllerGen.Crd
type ControllerGenCrdOpts struct {

	// Default: ["./..."]
	Paths []string

	// Default: "config/crd"
	Output string
}

func (r *ControllerGen) Crd(workspace *Workspace, opts ...ControllerGenCrdOpts) *Changeset {
	assertNotNil("workspace", workspace)
	q := r.query.Select("crd")
	for i := len(opts) - 1; i >= 0; i-- {
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
		// `output` optional argument
		if !querybuilder.IsZeroValue(opts[i].Output) {
			q = q.Arg("output", opts[i].Output)
		}
	}
	q = q.Arg("workspace", workspace)

	return &Changeset{
		query: q,
	}
}

// A unique identifier for this ControllerGen.
func (r *ControllerGen) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *ControllerGen) XXX_GraphQLType() string {
	return "ControllerGen"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *ControllerGen) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *ControllerGen) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *ControllerGen) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *ControllerGen) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = ControllerGen{query: selectNode(dag.query, id, "ControllerGen")}
	return nil
}

// ControllerGenObjectOpts contains options for ControllerGen.Object
type ControllerGenObjectOpts struct {

	// Default: ["./..."]
	Paths []string
}

func (r *ControllerGen) Object(opts ...ControllerGenObjectOpts) *Changeset {
	q := r.query.Select("object")
	for i := len(opts) - 1; i >= 0; i-- {
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
	}

	return &Changeset{
		query: q,
	}
}

// ControllerGenRbacOpts contains options for ControllerGen.Rbac
type ControllerGenRbacOpts struct {

	// Default: ["./..."]
	Paths []string

	// Default: "manager"
	RoleName string

	// Default: "config/rbac"
	Output string
}

func (r *ControllerGen) Rbac(opts ...ControllerGenRbacOpts) *Changeset {
	q := r.query.Select("rbac")
	for i := len(opts) - 1; i >= 0; i-- {
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
		// `roleName` optional argument
		if !querybuilder.IsZeroValue(opts[i].RoleName) {
			q = q.Arg("roleName", opts[i].RoleName)
		}
		// `output` optional argument
		if !querybuilder.IsZeroValue(opts[i].Output) {
			q = q.Arg("output", opts[i].Output)
		}
	}

	return &Changeset{
		query: q,
	}
}

// ControllerGenOpts contains options for Query.ControllerGen
type ControllerGenOpts struct {

	// Default: "."
	Path string

	Container *Container

	// Default: "v0.21.0"
	Version string
}

func (r *Query) ControllerGen(workspace *Workspace, opts ...ControllerGenOpts) *ControllerGen { // controller-gen (../../../:0:0)
	assertNotNil("workspace", workspace)
	q := r.query.Select("controllerGen")
	for i := len(opts) - 1; i >= 0; i-- {
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}
	q = q.Arg("workspace", workspace)

	return &ControllerGen{
		query: q,
	}
}
