// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Go struct { // go (../../../go/main.go:13:6)
	query *querybuilder.Selection

	id          *ID
	staticcheck *Void
	test        *Void
	vet         *Void
	vulncheck   *Void
}

func (r *Go) WithGraphQLQuery(q *querybuilder.Selection) *Go {
	return &Go{
		query: q,
	}
}

// GoBuildOpts contains options for Go.Build
type GoBuildOpts struct {

	// Default: "./"
	Pkg string // go (../../../go/main.go:104:2)

	// Default: "-s -w"
	Ldflags string // go (../../../go/main.go:107:2)

	Cgo bool // go (../../../go/main.go:109:2)

	Goarch string // go (../../../go/main.go:111:2)

	Goos string // go (../../../go/main.go:113:2)
}

func (r *Go) Build(opts ...GoBuildOpts) *File { // go (../../../go/main.go:100:1)
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `ldflags` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ldflags) {
			q = q.Arg("ldflags", opts[i].Ldflags)
		}
		// `cgo` optional argument
		if !querybuilder.IsZeroValue(opts[i].Cgo) {
			q = q.Arg("cgo", opts[i].Cgo)
		}
		// `goarch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goarch) {
			q = q.Arg("goarch", opts[i].Goarch)
		}
		// `goos` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goos) {
			q = q.Arg("goos", opts[i].Goos)
		}
	}

	return &File{
		query: q,
	}
}

func (r *Go) Container() *Container { // go (../../../go/main.go:14:2)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// GoFmtOpts contains options for Go.Fmt
type GoFmtOpts struct {

	// Default: "./..."
	Pkg string // go (../../../go/main.go:190:2)
}

func (r *Go) Fmt(opts ...GoFmtOpts) *Changeset { // go (../../../go/main.go:186:1)
	q := r.query.Select("fmt")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
	}

	return &Changeset{
		query: q,
	}
}

// GoGenerateOpts contains options for Go.Generate
type GoGenerateOpts struct {

	// Default: "./..."
	Pkg string // go (../../../go/main.go:264:2)
}

func (r *Go) Generate(opts ...GoGenerateOpts) *Changeset { // go (../../../go/main.go:260:1)
	q := r.query.Select("generate")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
	}

	return &Changeset{
		query: q,
	}
}

// A unique identifier for this Go.
func (r *Go) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Go) XXX_GraphQLType() string {
	return "Go"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Go) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Go) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Go) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Go) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Go{query: selectNode(dag.query, id, "Go")}
	return nil
}

// GoStaticcheckOpts contains options for Go.Staticcheck
type GoStaticcheckOpts struct {

	// Default: "./..."
	Pkg string // go (../../../go/main.go:233:2)

	// Default: "latest"
	Version string // go (../../../go/main.go:236:2)
}

func (r *Go) Staticcheck(ctx context.Context, opts ...GoStaticcheckOpts) error { // go (../../../go/main.go:229:1)
	if r.staticcheck != nil {
		return nil
	}
	q := r.query.Select("staticcheck")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return q.Execute(ctx)
}

// GoTestOpts contains options for Go.Test
type GoTestOpts struct {

	// Default: "."
	Path string // go (../../../go/main.go:152:2)

	// Default: "./..."
	Pkg string // go (../../../go/main.go:155:2)

	Race bool // go (../../../go/main.go:157:2)

	Cgo bool // go (../../../go/main.go:159:2)

	Tags []string // go (../../../go/main.go:161:2)
}

func (r *Go) Test(ctx context.Context, ws *Workspace, opts ...GoTestOpts) error { // go (../../../go/main.go:147:1)
	assertNotNil("ws", ws)
	if r.test != nil {
		return nil
	}
	q := r.query.Select("test")
	for i := len(opts) - 1; i >= 0; i-- {
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `race` optional argument
		if !querybuilder.IsZeroValue(opts[i].Race) {
			q = q.Arg("race", opts[i].Race)
		}
		// `cgo` optional argument
		if !querybuilder.IsZeroValue(opts[i].Cgo) {
			q = q.Arg("cgo", opts[i].Cgo)
		}
		// `tags` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tags) {
			q = q.Arg("tags", opts[i].Tags)
		}
	}
	q = q.Arg("ws", ws)

	return q.Execute(ctx)
}

// GoTidyOpts contains options for Go.Tidy
type GoTidyOpts struct {

	// Default: "."
	Path string // go (../../../go/main.go:251:2)
}

func (r *Go) Tidy(ws *Workspace, opts ...GoTidyOpts) *Changeset { // go (../../../go/main.go:246:1)
	assertNotNil("ws", ws)
	q := r.query.Select("tidy")
	for i := len(opts) - 1; i >= 0; i-- {
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
	}
	q = q.Arg("ws", ws)

	return &Changeset{
		query: q,
	}
}

// GoVetOpts contains options for Go.Vet
type GoVetOpts struct {

	// Default: "./..."
	Pkg string // go (../../../go/main.go:220:2)
}

func (r *Go) Vet(ctx context.Context, opts ...GoVetOpts) error { // go (../../../go/main.go:216:1)
	if r.vet != nil {
		return nil
	}
	q := r.query.Select("vet")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
	}

	return q.Execute(ctx)
}

// GoVulncheckOpts contains options for Go.Vulncheck
type GoVulncheckOpts struct {

	// Default: "./..."
	Pkg string // go (../../../go/main.go:203:2)

	// Default: "latest"
	Version string // go (../../../go/main.go:206:2)
}

func (r *Go) Vulncheck(ctx context.Context, opts ...GoVulncheckOpts) error { // go (../../../go/main.go:199:1)
	if r.vulncheck != nil {
		return nil
	}
	q := r.query.Select("vulncheck")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return q.Execute(ctx)
}

// AsNode returns this Go as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Go) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// GoOpts contains options for Query.Go
type GoOpts struct {

	// Default: "."
	Path string // go (../../../go/main.go:22:2)

	Container *Container // go (../../../go/main.go:24:2)
}

func (r *Query) Go(ws *Workspace, opts ...GoOpts) *Go { // go (../../../go/main.go:17:1)
	assertNotNil("ws", ws)
	q := r.query.Select("go")
	for i := len(opts) - 1; i >= 0; i-- {
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}
	q = q.Arg("ws", ws)

	return &Go{
		query: q,
	}
}
