// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// TrivyOpts contains options for Query.Trivy
type TrivyOpts struct {
	Modules *Directory

	Container *Container
}

func (r *Query) Trivy(opts ...TrivyOpts) *Trivy { // trivy (../../../:0:0)
	q := r.query.Select("trivy")
	for i := len(opts) - 1; i >= 0; i-- {
		// `modules` optional argument
		if !querybuilder.IsZeroValue(opts[i].Modules) {
			q = q.Arg("modules", opts[i].Modules)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Trivy{
		query: q,
	}
}

type Trivy struct { // trivy (../../../:0:0)
	query *querybuilder.Selection

	id    *ID
	image *Void
	repo  *Void
}

func (r *Trivy) WithGraphQLQuery(q *querybuilder.Selection) *Trivy {
	return &Trivy{
		query: q,
	}
}

func (r *Trivy) Container() *Container {
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// A unique identifier for this Trivy.
func (r *Trivy) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Trivy) XXX_GraphQLType() string {
	return "Trivy"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Trivy) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Trivy) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Trivy) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Trivy) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Trivy{query: selectNode(dag.query, id, "Trivy")}
	return nil
}

// TrivyImageOpts contains options for Trivy.Image
type TrivyImageOpts struct {
	DisableTelemtry bool

	OfflineScan bool

	SkipVersionCheck bool

	IgnoreUnfixed bool

	EnableModules []string

	Severity []string

	Scanners []string

	IgnoreStatus []string
}

func (r *Trivy) Image(ctx context.Context, container *Container, opts ...TrivyImageOpts) error {
	assertNotNil("container", container)
	if r.image != nil {
		return nil
	}
	q := r.query.Select("image")
	for i := len(opts) - 1; i >= 0; i-- {
		// `disableTelemtry` optional argument
		if !querybuilder.IsZeroValue(opts[i].DisableTelemtry) {
			q = q.Arg("disableTelemtry", opts[i].DisableTelemtry)
		}
		// `offlineScan` optional argument
		if !querybuilder.IsZeroValue(opts[i].OfflineScan) {
			q = q.Arg("offlineScan", opts[i].OfflineScan)
		}
		// `skipVersionCheck` optional argument
		if !querybuilder.IsZeroValue(opts[i].SkipVersionCheck) {
			q = q.Arg("skipVersionCheck", opts[i].SkipVersionCheck)
		}
		// `ignoreUnfixed` optional argument
		if !querybuilder.IsZeroValue(opts[i].IgnoreUnfixed) {
			q = q.Arg("ignoreUnfixed", opts[i].IgnoreUnfixed)
		}
		// `enableModules` optional argument
		if !querybuilder.IsZeroValue(opts[i].EnableModules) {
			q = q.Arg("enableModules", opts[i].EnableModules)
		}
		// `severity` optional argument
		if !querybuilder.IsZeroValue(opts[i].Severity) {
			q = q.Arg("severity", opts[i].Severity)
		}
		// `scanners` optional argument
		if !querybuilder.IsZeroValue(opts[i].Scanners) {
			q = q.Arg("scanners", opts[i].Scanners)
		}
		// `ignoreStatus` optional argument
		if !querybuilder.IsZeroValue(opts[i].IgnoreStatus) {
			q = q.Arg("ignoreStatus", opts[i].IgnoreStatus)
		}
	}
	q = q.Arg("container", container)

	return q.Execute(ctx)
}

// TrivyRepoOpts contains options for Trivy.Repo
type TrivyRepoOpts struct {

	// Default: "."
	Path string

	DisableTelemtry bool

	OfflineScan bool

	SkipVersionCheck bool

	IgnoreUnfixed bool

	EnableModules []string

	Severity []string

	Scanners []string

	IgnoreStatus []string
}

func (r *Trivy) Repo(ctx context.Context, workspace *Workspace, opts ...TrivyRepoOpts) error {
	assertNotNil("workspace", workspace)
	if r.repo != nil {
		return nil
	}
	q := r.query.Select("repo")
	for i := len(opts) - 1; i >= 0; i-- {
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
		// `disableTelemtry` optional argument
		if !querybuilder.IsZeroValue(opts[i].DisableTelemtry) {
			q = q.Arg("disableTelemtry", opts[i].DisableTelemtry)
		}
		// `offlineScan` optional argument
		if !querybuilder.IsZeroValue(opts[i].OfflineScan) {
			q = q.Arg("offlineScan", opts[i].OfflineScan)
		}
		// `skipVersionCheck` optional argument
		if !querybuilder.IsZeroValue(opts[i].SkipVersionCheck) {
			q = q.Arg("skipVersionCheck", opts[i].SkipVersionCheck)
		}
		// `ignoreUnfixed` optional argument
		if !querybuilder.IsZeroValue(opts[i].IgnoreUnfixed) {
			q = q.Arg("ignoreUnfixed", opts[i].IgnoreUnfixed)
		}
		// `enableModules` optional argument
		if !querybuilder.IsZeroValue(opts[i].EnableModules) {
			q = q.Arg("enableModules", opts[i].EnableModules)
		}
		// `severity` optional argument
		if !querybuilder.IsZeroValue(opts[i].Severity) {
			q = q.Arg("severity", opts[i].Severity)
		}
		// `scanners` optional argument
		if !querybuilder.IsZeroValue(opts[i].Scanners) {
			q = q.Arg("scanners", opts[i].Scanners)
		}
		// `ignoreStatus` optional argument
		if !querybuilder.IsZeroValue(opts[i].IgnoreStatus) {
			q = q.Arg("ignoreStatus", opts[i].IgnoreStatus)
		}
	}
	q = q.Arg("workspace", workspace)

	return q.Execute(ctx)
}
