// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"github.com/frantjc/daggerverse/trivy/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Trivy) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Container *dagger.Container
	}
	concrete.Container = r.Container
	return json.Marshal(&concrete)
}

func (r *Trivy) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Container *dagger.Container
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Container = concrete.Container
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Trivy":
		switch fnName {
		case "Image":
			var parent Trivy
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			var disableTelemtry bool
			if inputArgs["disableTelemtry"] != nil {
				err = json.Unmarshal([]byte(inputArgs["disableTelemtry"]), &disableTelemtry)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg disableTelemtry", err))
				}
			}
			var offlineScan bool
			if inputArgs["offlineScan"] != nil {
				err = json.Unmarshal([]byte(inputArgs["offlineScan"]), &offlineScan)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg offlineScan", err))
				}
			}
			var skipVersionCheck bool
			if inputArgs["skipVersionCheck"] != nil {
				err = json.Unmarshal([]byte(inputArgs["skipVersionCheck"]), &skipVersionCheck)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg skipVersionCheck", err))
				}
			}
			var ignoreUnfixed bool
			if inputArgs["ignoreUnfixed"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ignoreUnfixed"]), &ignoreUnfixed)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ignoreUnfixed", err))
				}
			}
			var enableModules []string
			if inputArgs["enableModules"] != nil {
				err = json.Unmarshal([]byte(inputArgs["enableModules"]), &enableModules)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg enableModules", err))
				}
			}
			var severity []string
			if inputArgs["severity"] != nil {
				err = json.Unmarshal([]byte(inputArgs["severity"]), &severity)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg severity", err))
				}
			}
			var scanners []string
			if inputArgs["scanners"] != nil {
				err = json.Unmarshal([]byte(inputArgs["scanners"]), &scanners)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg scanners", err))
				}
			}
			var ignoreStatus []string
			if inputArgs["ignoreStatus"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ignoreStatus"]), &ignoreStatus)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ignoreStatus", err))
				}
			}
			return nil, (*Trivy).Image(&parent, ctx, container, disableTelemtry, offlineScan, skipVersionCheck, ignoreUnfixed, enableModules, severity, scanners, ignoreStatus)
		case "Repo":
			var parent Trivy
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var workspace *dagger.Workspace
			if inputArgs["workspace"] != nil {
				err = json.Unmarshal([]byte(inputArgs["workspace"]), &workspace)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg workspace", err))
				}
			}
			var path string
			if inputArgs["path"] != nil {
				err = json.Unmarshal([]byte(inputArgs["path"]), &path)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg path", err))
				}
			}
			var disableTelemtry bool
			if inputArgs["disableTelemtry"] != nil {
				err = json.Unmarshal([]byte(inputArgs["disableTelemtry"]), &disableTelemtry)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg disableTelemtry", err))
				}
			}
			var offlineScan bool
			if inputArgs["offlineScan"] != nil {
				err = json.Unmarshal([]byte(inputArgs["offlineScan"]), &offlineScan)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg offlineScan", err))
				}
			}
			var skipVersionCheck bool
			if inputArgs["skipVersionCheck"] != nil {
				err = json.Unmarshal([]byte(inputArgs["skipVersionCheck"]), &skipVersionCheck)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg skipVersionCheck", err))
				}
			}
			var ignoreUnfixed bool
			if inputArgs["ignoreUnfixed"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ignoreUnfixed"]), &ignoreUnfixed)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ignoreUnfixed", err))
				}
			}
			var enableModules []string
			if inputArgs["enableModules"] != nil {
				err = json.Unmarshal([]byte(inputArgs["enableModules"]), &enableModules)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg enableModules", err))
				}
			}
			var severity []string
			if inputArgs["severity"] != nil {
				err = json.Unmarshal([]byte(inputArgs["severity"]), &severity)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg severity", err))
				}
			}
			var scanners []string
			if inputArgs["scanners"] != nil {
				err = json.Unmarshal([]byte(inputArgs["scanners"]), &scanners)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg scanners", err))
				}
			}
			var ignoreStatus []string
			if inputArgs["ignoreStatus"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ignoreStatus"]), &ignoreStatus)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ignoreStatus", err))
				}
			}
			return nil, (*Trivy).Repo(&parent, ctx, workspace, path, disableTelemtry, offlineScan, skipVersionCheck, ignoreUnfixed, enableModules, severity, scanners, ignoreStatus)
		case "":
			var parent Trivy
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var modules *dagger.Directory
			if inputArgs["modules"] != nil {
				err = json.Unmarshal([]byte(inputArgs["modules"]), &modules)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg modules", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return New(ctx, modules, container), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithDescription("A generated module for Trivy functions\n").
			WithObject(
				dag.TypeDef().WithObject("Trivy", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 13, 6)}).
					WithFunction(
						dag.Function("Image",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithSourceMap(dag.SourceMap("main.go", 114, 1)).
							WithArg("container", dag.TypeDef().WithObject("Container"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 116, 2)}).
							WithArg("disableTelemtry", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 118, 2)}).
							WithArg("offlineScan", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 120, 2)}).
							WithArg("skipVersionCheck", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 122, 2)}).
							WithArg("ignoreUnfixed", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 124, 2)}).
							WithArg("enableModules", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 126, 2)}).
							WithArg("severity", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 128, 2)}).
							WithArg("scanners", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 130, 2)}).
							WithArg("ignoreStatus", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 132, 2)})).
					WithFunction(
						dag.Function("Repo",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithSourceMap(dag.SourceMap("main.go", 61, 1)).
							WithCheck().
							WithArg("workspace", dag.TypeDef().WithObject("Workspace"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 63, 2)}).
							WithArg("path", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 66, 2), DefaultValue: dagger.JSON("\".\"")}).
							WithArg("disableTelemtry", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 68, 2)}).
							WithArg("offlineScan", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 70, 2)}).
							WithArg("skipVersionCheck", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 72, 2)}).
							WithArg("ignoreUnfixed", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 74, 2)}).
							WithArg("enableModules", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 76, 2)}).
							WithArg("severity", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 78, 2)}).
							WithArg("scanners", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 80, 2)}).
							WithArg("ignoreStatus", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 82, 2)})).
					WithField("Container", dag.TypeDef().WithObject("Container"), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("main.go", 14, 2)}).
					WithConstructor(
						dag.Function("New",
							dag.TypeDef().WithObject("Trivy")).
							WithSourceMap(dag.SourceMap("main.go", 17, 1)).
							WithArg("modules", dag.TypeDef().WithObject("Directory").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 20, 2)}).
							WithArg("container", dag.TypeDef().WithObject("Container").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 23, 2), DefaultAddress: "docker.io/aquasec/trivy:0.72.0"}))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
