// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Godot struct { // godot (../../../:0:0)
	query *querybuilder.Selection

	id *ID
}

func (r *Godot) WithGraphQLQuery(q *querybuilder.Selection) *Godot {
	return &Godot{
		query: q,
	}
}

func (r *Godot) Container() *Container {
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// GodotExportDebugOpts contains options for Godot.ExportDebug
type GodotExportDebugOpts struct {
	OsslsigncodeVersion string

	ScriptEncryptionKey *Secret

	WindowsCodesignIdentityType string

	WindowsCodesignIdentity *File

	WindowsCodesignPassword *Secret
}

func (r *Godot) ExportDebug(src *Directory, preset string, path string, opts ...GodotExportDebugOpts) *GodotExport {
	assertNotNil("src", src)
	q := r.query.Select("exportDebug")
	for i := len(opts) - 1; i >= 0; i-- {
		// `osslsigncodeVersion` optional argument
		if !querybuilder.IsZeroValue(opts[i].OsslsigncodeVersion) {
			q = q.Arg("osslsigncodeVersion", opts[i].OsslsigncodeVersion)
		}
		// `scriptEncryptionKey` optional argument
		if !querybuilder.IsZeroValue(opts[i].ScriptEncryptionKey) {
			q = q.Arg("scriptEncryptionKey", opts[i].ScriptEncryptionKey)
		}
		// `windowsCodesignIdentityType` optional argument
		if !querybuilder.IsZeroValue(opts[i].WindowsCodesignIdentityType) {
			q = q.Arg("windowsCodesignIdentityType", opts[i].WindowsCodesignIdentityType)
		}
		// `windowsCodesignIdentity` optional argument
		if !querybuilder.IsZeroValue(opts[i].WindowsCodesignIdentity) {
			q = q.Arg("windowsCodesignIdentity", opts[i].WindowsCodesignIdentity)
		}
		// `windowsCodesignPassword` optional argument
		if !querybuilder.IsZeroValue(opts[i].WindowsCodesignPassword) {
			q = q.Arg("windowsCodesignPassword", opts[i].WindowsCodesignPassword)
		}
	}
	q = q.Arg("src", src)
	q = q.Arg("preset", preset)
	q = q.Arg("path", path)

	return &GodotExport{
		query: q,
	}
}

// GodotExportReleaseOpts contains options for Godot.ExportRelease
type GodotExportReleaseOpts struct {
	OsslsigncodeVersion string

	ScriptEncryptionKey *Secret

	WindowsCodesignIdentityType string

	WindowsCodesignIdentity *File

	WindowsCodesignPassword *Secret
}

func (r *Godot) ExportRelease(src *Directory, preset string, path string, opts ...GodotExportReleaseOpts) *GodotExport {
	assertNotNil("src", src)
	q := r.query.Select("exportRelease")
	for i := len(opts) - 1; i >= 0; i-- {
		// `osslsigncodeVersion` optional argument
		if !querybuilder.IsZeroValue(opts[i].OsslsigncodeVersion) {
			q = q.Arg("osslsigncodeVersion", opts[i].OsslsigncodeVersion)
		}
		// `scriptEncryptionKey` optional argument
		if !querybuilder.IsZeroValue(opts[i].ScriptEncryptionKey) {
			q = q.Arg("scriptEncryptionKey", opts[i].ScriptEncryptionKey)
		}
		// `windowsCodesignIdentityType` optional argument
		if !querybuilder.IsZeroValue(opts[i].WindowsCodesignIdentityType) {
			q = q.Arg("windowsCodesignIdentityType", opts[i].WindowsCodesignIdentityType)
		}
		// `windowsCodesignIdentity` optional argument
		if !querybuilder.IsZeroValue(opts[i].WindowsCodesignIdentity) {
			q = q.Arg("windowsCodesignIdentity", opts[i].WindowsCodesignIdentity)
		}
		// `windowsCodesignPassword` optional argument
		if !querybuilder.IsZeroValue(opts[i].WindowsCodesignPassword) {
			q = q.Arg("windowsCodesignPassword", opts[i].WindowsCodesignPassword)
		}
	}
	q = q.Arg("src", src)
	q = q.Arg("preset", preset)
	q = q.Arg("path", path)

	return &GodotExport{
		query: q,
	}
}

func (r *Godot) ExportTemplates() *Directory {
	q := r.query.Select("exportTemplates")

	return &Directory{
		query: q,
	}
}

// A unique identifier for this Godot.
func (r *Godot) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Godot) XXX_GraphQLType() string {
	return "Godot"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Godot) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Godot) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Godot) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Godot) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Godot{query: selectNode(dag.query, id, "Godot")}
	return nil
}

type GodotExport struct { // godot (../../../:0:0)
	query *querybuilder.Selection

	id *ID
}

func (r *GodotExport) WithGraphQLQuery(q *querybuilder.Selection) *GodotExport {
	return &GodotExport{
		query: q,
	}
}

func (r *GodotExport) Binary() *File {
	q := r.query.Select("binary")

	return &File{
		query: q,
	}
}

// A unique identifier for this GodotExport.
func (r *GodotExport) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *GodotExport) XXX_GraphQLType() string {
	return "GodotExport"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *GodotExport) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *GodotExport) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *GodotExport) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *GodotExport) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = GodotExport{query: selectNode(dag.query, id, "GodotExport")}
	return nil
}

func (r *GodotExport) Pck() *File {
	q := r.query.Select("pck")

	return &File{
		query: q,
	}
}

// GodotOpts contains options for Query.Godot
type GodotOpts struct {

	// Default: "4.6.1"
	Version string

	// Default: "stable"
	Flavor string

	Container *Container
}

func (r *Query) Godot(opts ...GodotOpts) *Godot { // godot (../../../:0:0)
	q := r.query.Select("godot")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `flavor` optional argument
		if !querybuilder.IsZeroValue(opts[i].Flavor) {
			q = q.Arg("flavor", opts[i].Flavor)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Godot{
		query: q,
	}
}
