// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Arch struct { // arch (../../../:0:0)
	query *querybuilder.Selection

	gnu       *string
	id        *ID
	microsoft *string
	oci       *string
}

func (r *Arch) WithGraphQLQuery(q *querybuilder.Selection) *Arch {
	return &Arch{
		query: q,
	}
}

// GNU returns the architecture in GNU/uname naming (e.g. "x86_64", "aarch64").
func (r *Arch) Gnu(ctx context.Context) (string, error) {
	if r.gnu != nil {
		return *r.gnu, nil
	}
	q := r.query.Select("gnu")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this Arch.
func (r *Arch) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Arch) XXX_GraphQLType() string {
	return "Arch"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Arch) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Arch) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Arch) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Arch) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Arch{query: selectNode(dag.query, id, "Arch")}
	return nil
}

// Microsoft returns the architecture in Microsoft naming (e.g. "x64", "arm64").
func (r *Arch) Microsoft(ctx context.Context) (string, error) {
	if r.microsoft != nil {
		return *r.microsoft, nil
	}
	q := r.query.Select("microsoft")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// OCI returns the architecture in OCI/Go naming (e.g. "amd64", "arm64").
func (r *Arch) Oci(ctx context.Context) (string, error) {
	if r.oci != nil {
		return *r.oci, nil
	}
	q := r.query.Select("oci")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *Query) Arch() *Arch { // arch (../../../:0:0)
	q := r.query.Select("arch")

	return &Arch{
		query: q,
	}
}
