// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"github.com/frantjc/daggerverse/go/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Go) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Container *dagger.Container
	}
	concrete.Container = r.Container
	return json.Marshal(&concrete)
}

func (r *Go) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Container *dagger.Container
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Container = concrete.Container
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Go":
		switch fnName {
		case "Build":
			var parent Go
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var pkg string
			if inputArgs["pkg"] != nil {
				err = json.Unmarshal([]byte(inputArgs["pkg"]), &pkg)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg pkg", err))
				}
			}
			var ldflags string
			if inputArgs["ldflags"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ldflags"]), &ldflags)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ldflags", err))
				}
			}
			var cgo bool
			if inputArgs["cgo"] != nil {
				err = json.Unmarshal([]byte(inputArgs["cgo"]), &cgo)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg cgo", err))
				}
			}
			var goarch string
			if inputArgs["goarch"] != nil {
				err = json.Unmarshal([]byte(inputArgs["goarch"]), &goarch)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg goarch", err))
				}
			}
			var goos string
			if inputArgs["goos"] != nil {
				err = json.Unmarshal([]byte(inputArgs["goos"]), &goos)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg goos", err))
				}
			}
			return (*Go).Build(&parent, ctx, pkg, ldflags, cgo, goarch, goos)
		case "Fmt":
			var parent Go
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var pkg string
			if inputArgs["pkg"] != nil {
				err = json.Unmarshal([]byte(inputArgs["pkg"]), &pkg)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg pkg", err))
				}
			}
			return (*Go).Fmt(&parent, ctx, pkg)
		case "Generate":
			var parent Go
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var pkg string
			if inputArgs["pkg"] != nil {
				err = json.Unmarshal([]byte(inputArgs["pkg"]), &pkg)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg pkg", err))
				}
			}
			return (*Go).Generate(&parent, ctx, pkg)
		case "Staticcheck":
			var parent Go
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var pkg string
			if inputArgs["pkg"] != nil {
				err = json.Unmarshal([]byte(inputArgs["pkg"]), &pkg)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg pkg", err))
				}
			}
			var version string
			if inputArgs["version"] != nil {
				err = json.Unmarshal([]byte(inputArgs["version"]), &version)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg version", err))
				}
			}
			return nil, (*Go).Staticcheck(&parent, ctx, pkg, version)
		case "Test":
			var parent Go
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var workspace *dagger.Workspace
			if inputArgs["workspace"] != nil {
				err = json.Unmarshal([]byte(inputArgs["workspace"]), &workspace)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg workspace", err))
				}
			}
			var path string
			if inputArgs["path"] != nil {
				err = json.Unmarshal([]byte(inputArgs["path"]), &path)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg path", err))
				}
			}
			var pkg string
			if inputArgs["pkg"] != nil {
				err = json.Unmarshal([]byte(inputArgs["pkg"]), &pkg)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg pkg", err))
				}
			}
			var race bool
			if inputArgs["race"] != nil {
				err = json.Unmarshal([]byte(inputArgs["race"]), &race)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg race", err))
				}
			}
			var cgo bool
			if inputArgs["cgo"] != nil {
				err = json.Unmarshal([]byte(inputArgs["cgo"]), &cgo)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg cgo", err))
				}
			}
			var tags []string
			if inputArgs["tags"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tags"]), &tags)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tags", err))
				}
			}
			return nil, (*Go).Test(&parent, ctx, workspace, path, pkg, race, cgo, tags)
		case "Tidy":
			var parent Go
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var workspace *dagger.Workspace
			if inputArgs["workspace"] != nil {
				err = json.Unmarshal([]byte(inputArgs["workspace"]), &workspace)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg workspace", err))
				}
			}
			var path string
			if inputArgs["path"] != nil {
				err = json.Unmarshal([]byte(inputArgs["path"]), &path)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg path", err))
				}
			}
			return (*Go).Tidy(&parent, ctx, workspace, path)
		case "Vet":
			var parent Go
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var pkg string
			if inputArgs["pkg"] != nil {
				err = json.Unmarshal([]byte(inputArgs["pkg"]), &pkg)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg pkg", err))
				}
			}
			return nil, (*Go).Vet(&parent, ctx, pkg)
		case "Vulncheck":
			var parent Go
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var pkg string
			if inputArgs["pkg"] != nil {
				err = json.Unmarshal([]byte(inputArgs["pkg"]), &pkg)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg pkg", err))
				}
			}
			var version string
			if inputArgs["version"] != nil {
				err = json.Unmarshal([]byte(inputArgs["version"]), &version)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg version", err))
				}
			}
			return nil, (*Go).Vulncheck(&parent, ctx, pkg, version)
		case "":
			var parent Go
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var workspace *dagger.Workspace
			if inputArgs["workspace"] != nil {
				err = json.Unmarshal([]byte(inputArgs["workspace"]), &workspace)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg workspace", err))
				}
			}
			var path string
			if inputArgs["path"] != nil {
				err = json.Unmarshal([]byte(inputArgs["path"]), &path)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg path", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return New(ctx, workspace, path, container)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithObject(
				dag.TypeDef().WithObject("Go", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 13, 6)}).
					WithFunction(
						dag.Function("Build",
							dag.TypeDef().WithObject("File")).
							WithSourceMap(dag.SourceMap("main.go", 101, 1)).
							WithArg("pkg", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 105, 2), DefaultValue: dagger.JSON("\"./\"")}).
							WithArg("ldflags", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 108, 2), DefaultValue: dagger.JSON("\"-s -w\"")}).
							WithArg("cgo", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 110, 2)}).
							WithArg("goarch", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 112, 2)}).
							WithArg("goos", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 114, 2)})).
					WithFunction(
						dag.Function("Fmt",
							dag.TypeDef().WithObject("Changeset")).
							WithSourceMap(dag.SourceMap("main.go", 187, 1)).
							WithGenerator().
							WithArg("pkg", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 191, 2), DefaultValue: dagger.JSON("\"./...\"")})).
					WithFunction(
						dag.Function("Generate",
							dag.TypeDef().WithObject("Changeset")).
							WithSourceMap(dag.SourceMap("main.go", 261, 1)).
							WithGenerator().
							WithArg("pkg", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 265, 2), DefaultValue: dagger.JSON("\"./...\"")})).
					WithFunction(
						dag.Function("Staticcheck",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithSourceMap(dag.SourceMap("main.go", 230, 1)).
							WithCheck().
							WithArg("pkg", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 234, 2), DefaultValue: dagger.JSON("\"./...\"")}).
							WithArg("version", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 237, 2), DefaultValue: dagger.JSON("\"latest\"")})).
					WithFunction(
						dag.Function("Test",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithSourceMap(dag.SourceMap("main.go", 148, 1)).
							WithCheck().
							WithArg("workspace", dag.TypeDef().WithObject("Workspace"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 150, 2)}).
							WithArg("path", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 153, 2), DefaultValue: dagger.JSON("\".\"")}).
							WithArg("pkg", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 156, 2), DefaultValue: dagger.JSON("\"./...\"")}).
							WithArg("race", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 158, 2)}).
							WithArg("cgo", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 160, 2)}).
							WithArg("tags", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 162, 2)})).
					WithFunction(
						dag.Function("Tidy",
							dag.TypeDef().WithObject("Changeset")).
							WithSourceMap(dag.SourceMap("main.go", 247, 1)).
							WithGenerator().
							WithArg("workspace", dag.TypeDef().WithObject("Workspace"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 249, 2)}).
							WithArg("path", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 252, 2), DefaultValue: dagger.JSON("\".\"")})).
					WithFunction(
						dag.Function("Vet",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithSourceMap(dag.SourceMap("main.go", 217, 1)).
							WithCheck().
							WithArg("pkg", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 221, 2), DefaultValue: dagger.JSON("\"./...\"")})).
					WithFunction(
						dag.Function("Vulncheck",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithSourceMap(dag.SourceMap("main.go", 200, 1)).
							WithCheck().
							WithArg("pkg", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 204, 2), DefaultValue: dagger.JSON("\"./...\"")}).
							WithArg("version", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 207, 2), DefaultValue: dagger.JSON("\"latest\"")})).
					WithField("Container", dag.TypeDef().WithObject("Container"), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("main.go", 14, 2)}).
					WithConstructor(
						dag.Function("New",
							dag.TypeDef().WithObject("Go")).
							WithSourceMap(dag.SourceMap("main.go", 17, 1)).
							WithArg("workspace", dag.TypeDef().WithObject("Workspace"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 19, 2)}).
							WithArg("path", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 22, 2), DefaultValue: dagger.JSON("\".\"")}).
							WithArg("container", dag.TypeDef().WithObject("Container").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 24, 2)}))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
