// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"github.com/frantjc/daggerverse/kwok/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Kwok) MarshalJSON() ([]byte, error) {
	var concrete struct{}
	return json.Marshal(&concrete)
}

func (r *Kwok) UnmarshalJSON(bs []byte) error {
	var concrete struct{}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	return nil
}

func (r Cluster) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Container                 *dagger.Container
		KubeApiserverInsecurePort int
	}
	concrete.Container = r.Container
	concrete.KubeApiserverInsecurePort = r.KubeApiserverInsecurePort
	return json.Marshal(&concrete)
}

func (r *Cluster) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Container                 *dagger.Container
		KubeApiserverInsecurePort int
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Container = concrete.Container
	r.KubeApiserverInsecurePort = concrete.KubeApiserverInsecurePort
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Cluster":
		switch fnName {
		case "KubeConfig":
			var parent Cluster
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var alias string
			if inputArgs["alias"] != nil {
				err = json.Unmarshal([]byte(inputArgs["alias"]), &alias)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg alias", err))
				}
			}
			return (*Cluster).KubeConfig(&parent, ctx, alias)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Kwok":
		switch fnName {
		case "Cluster":
			var parent Kwok
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			var components []string
			if inputArgs["components"] != nil {
				err = json.Unmarshal([]byte(inputArgs["components"]), &components)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg components", err))
				}
			}
			var controllerPort int
			if inputArgs["controllerPort"] != nil {
				err = json.Unmarshal([]byte(inputArgs["controllerPort"]), &controllerPort)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg controllerPort", err))
				}
			}
			var disable []string
			if inputArgs["disable"] != nil {
				err = json.Unmarshal([]byte(inputArgs["disable"]), &disable)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg disable", err))
				}
			}
			var disableQpslimits bool
			if inputArgs["disableQPSLimits"] != nil {
				err = json.Unmarshal([]byte(inputArgs["disableQPSLimits"]), &disableQpslimits)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg disableQPSLimits", err))
				}
			}
			var enable []string
			if inputArgs["enable"] != nil {
				err = json.Unmarshal([]byte(inputArgs["enable"]), &enable)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg enable", err))
				}
			}
			var enableCrds []string
			if inputArgs["enableCRDs"] != nil {
				err = json.Unmarshal([]byte(inputArgs["enableCRDs"]), &enableCrds)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg enableCRDs", err))
				}
			}
			var kubeApiserverInsecurePort int
			if inputArgs["kubeApiserverInsecurePort"] != nil {
				err = json.Unmarshal([]byte(inputArgs["kubeApiserverInsecurePort"]), &kubeApiserverInsecurePort)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg kubeApiserverInsecurePort", err))
				}
			}
			var kubeAuditPolicy *dagger.File
			if inputArgs["kubeAuditPolicy"] != nil {
				err = json.Unmarshal([]byte(inputArgs["kubeAuditPolicy"]), &kubeAuditPolicy)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg kubeAuditPolicy", err))
				}
			}
			var etcd *dagger.File
			if inputArgs["etcd"] != nil {
				err = json.Unmarshal([]byte(inputArgs["etcd"]), &etcd)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg etcd", err))
				}
			}
			var jaeger *dagger.File
			if inputArgs["jaeger"] != nil {
				err = json.Unmarshal([]byte(inputArgs["jaeger"]), &jaeger)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg jaeger", err))
				}
			}
			var kubeApiserver *dagger.File
			if inputArgs["kubeApiserver"] != nil {
				err = json.Unmarshal([]byte(inputArgs["kubeApiserver"]), &kubeApiserver)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg kubeApiserver", err))
				}
			}
			var kubeScheduler *dagger.File
			if inputArgs["kubeScheduler"] != nil {
				err = json.Unmarshal([]byte(inputArgs["kubeScheduler"]), &kubeScheduler)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg kubeScheduler", err))
				}
			}
			var kubeControllerManager *dagger.File
			if inputArgs["kubeControllerManager"] != nil {
				err = json.Unmarshal([]byte(inputArgs["kubeControllerManager"]), &kubeControllerManager)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg kubeControllerManager", err))
				}
			}
			var kwokController *dagger.File
			if inputArgs["kwokController"] != nil {
				err = json.Unmarshal([]byte(inputArgs["kwokController"]), &kwokController)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg kwokController", err))
				}
			}
			var metricsServer *dagger.File
			if inputArgs["metricsServer"] != nil {
				err = json.Unmarshal([]byte(inputArgs["metricsServer"]), &metricsServer)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg metricsServer", err))
				}
			}
			var prometheus *dagger.File
			if inputArgs["prometheus"] != nil {
				err = json.Unmarshal([]byte(inputArgs["prometheus"]), &prometheus)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg prometheus", err))
				}
			}
			return (*Kwok).Cluster(&parent, ctx, container, components, controllerPort, disable, disableQpslimits, enable, enableCrds, kubeApiserverInsecurePort, kubeAuditPolicy, etcd, jaeger, kubeApiserver, kubeScheduler, kubeControllerManager, kwokController, metricsServer, prometheus)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithObject(
				dag.TypeDef().WithObject("Kwok", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 16, 6)}).
					WithFunction(
						dag.Function("Cluster",
							dag.TypeDef().WithObject("Cluster")).
							WithSourceMap(dag.SourceMap("main.go", 55, 1)).
							WithArg("container", dag.TypeDef().WithObject("Container").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 59, 2), DefaultAddress: "registry.k8s.io/kwok/cluster:v0.7.0-k8s.v1.33.0"}).
							WithArg("components", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 61, 2)}).
							WithArg("controllerPort", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 63, 2)}).
							WithArg("disable", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 65, 2)}).
							WithArg("disableQPSLimits", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 67, 2)}).
							WithArg("enable", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 69, 2)}).
							WithArg("enableCRDs", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 71, 2)}).
							WithArg("kubeApiserverInsecurePort", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 74, 2), DefaultValue: dagger.JSON("8080")}).
							WithArg("kubeAuditPolicy", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 76, 2)}).
							WithArg("etcd", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 78, 2)}).
							WithArg("jaeger", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 80, 2)}).
							WithArg("kubeApiserver", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 82, 2)}).
							WithArg("kubeScheduler", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 84, 2)}).
							WithArg("kubeControllerManager", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 86, 2)}).
							WithArg("kwokController", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 88, 2)}).
							WithArg("metricsServer", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 90, 2)}).
							WithArg("prometheus", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 92, 2)}))).
			WithObject(
				dag.TypeDef().WithObject("Cluster", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 218, 6)}).
					WithFunction(
						dag.Function("KubeConfig",
							dag.TypeDef().WithObject("File")).
							WithSourceMap(dag.SourceMap("main.go", 224, 1)).
							WithArg("alias", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 228, 2), DefaultValue: dagger.JSON("\"kwok\"")})).
					WithField("Container", dag.TypeDef().WithObject("Container"), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("main.go", 219, 2)})), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
