// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Kwok struct { // kwok (../../../:0:0)
	query *querybuilder.Selection

	id *ID
}

func (r *Kwok) WithGraphQLQuery(q *querybuilder.Selection) *Kwok {
	return &Kwok{
		query: q,
	}
}

// KwokClusterOpts contains options for Kwok.Cluster
type KwokClusterOpts struct {
	Container *Container

	Components []string

	ControllerPort int

	Disable []string

	DisableQpslimits bool

	Enable []string

	EnableCrds []string

	// Default: 8080
	KubeApiserverInsecurePort int

	KubeAuditPolicy *File

	Etcd *File

	Jaeger *File

	KubeApiserver *File

	KubeScheduler *File

	KubeControllerManager *File

	KwokController *File

	MetricsServer *File

	Prometheus *File
}

func (r *Kwok) Cluster(opts ...KwokClusterOpts) *KwokCluster {
	q := r.query.Select("cluster")
	for i := len(opts) - 1; i >= 0; i-- {
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
		// `components` optional argument
		if !querybuilder.IsZeroValue(opts[i].Components) {
			q = q.Arg("components", opts[i].Components)
		}
		// `controllerPort` optional argument
		if !querybuilder.IsZeroValue(opts[i].ControllerPort) {
			q = q.Arg("controllerPort", opts[i].ControllerPort)
		}
		// `disable` optional argument
		if !querybuilder.IsZeroValue(opts[i].Disable) {
			q = q.Arg("disable", opts[i].Disable)
		}
		// `disableQpslimits` optional argument
		if !querybuilder.IsZeroValue(opts[i].DisableQpslimits) {
			q = q.Arg("disableQpslimits", opts[i].DisableQpslimits)
		}
		// `enable` optional argument
		if !querybuilder.IsZeroValue(opts[i].Enable) {
			q = q.Arg("enable", opts[i].Enable)
		}
		// `enableCrds` optional argument
		if !querybuilder.IsZeroValue(opts[i].EnableCrds) {
			q = q.Arg("enableCrds", opts[i].EnableCrds)
		}
		// `kubeApiserverInsecurePort` optional argument
		if !querybuilder.IsZeroValue(opts[i].KubeApiserverInsecurePort) {
			q = q.Arg("kubeApiserverInsecurePort", opts[i].KubeApiserverInsecurePort)
		}
		// `kubeAuditPolicy` optional argument
		if !querybuilder.IsZeroValue(opts[i].KubeAuditPolicy) {
			q = q.Arg("kubeAuditPolicy", opts[i].KubeAuditPolicy)
		}
		// `etcd` optional argument
		if !querybuilder.IsZeroValue(opts[i].Etcd) {
			q = q.Arg("etcd", opts[i].Etcd)
		}
		// `jaeger` optional argument
		if !querybuilder.IsZeroValue(opts[i].Jaeger) {
			q = q.Arg("jaeger", opts[i].Jaeger)
		}
		// `kubeApiserver` optional argument
		if !querybuilder.IsZeroValue(opts[i].KubeApiserver) {
			q = q.Arg("kubeApiserver", opts[i].KubeApiserver)
		}
		// `kubeScheduler` optional argument
		if !querybuilder.IsZeroValue(opts[i].KubeScheduler) {
			q = q.Arg("kubeScheduler", opts[i].KubeScheduler)
		}
		// `kubeControllerManager` optional argument
		if !querybuilder.IsZeroValue(opts[i].KubeControllerManager) {
			q = q.Arg("kubeControllerManager", opts[i].KubeControllerManager)
		}
		// `kwokController` optional argument
		if !querybuilder.IsZeroValue(opts[i].KwokController) {
			q = q.Arg("kwokController", opts[i].KwokController)
		}
		// `metricsServer` optional argument
		if !querybuilder.IsZeroValue(opts[i].MetricsServer) {
			q = q.Arg("metricsServer", opts[i].MetricsServer)
		}
		// `prometheus` optional argument
		if !querybuilder.IsZeroValue(opts[i].Prometheus) {
			q = q.Arg("prometheus", opts[i].Prometheus)
		}
	}

	return &KwokCluster{
		query: q,
	}
}

// A unique identifier for this Kwok.
func (r *Kwok) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Kwok) XXX_GraphQLType() string {
	return "Kwok"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Kwok) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Kwok) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Kwok) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Kwok) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Kwok{query: selectNode(dag.query, id, "Kwok")}
	return nil
}

type KwokCluster struct { // kwok (../../../:0:0)
	query *querybuilder.Selection

	id *ID
}

func (r *KwokCluster) WithGraphQLQuery(q *querybuilder.Selection) *KwokCluster {
	return &KwokCluster{
		query: q,
	}
}

func (r *KwokCluster) Container() *Container {
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// A unique identifier for this KwokCluster.
func (r *KwokCluster) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *KwokCluster) XXX_GraphQLType() string {
	return "KwokCluster"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *KwokCluster) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *KwokCluster) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *KwokCluster) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *KwokCluster) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = KwokCluster{query: selectNode(dag.query, id, "KwokCluster")}
	return nil
}

// KwokClusterKubeConfigOpts contains options for KwokCluster.KubeConfig
type KwokClusterKubeConfigOpts struct {

	// Default: "kwok"
	Alias string
}

func (r *KwokCluster) KubeConfig(opts ...KwokClusterKubeConfigOpts) *File {
	q := r.query.Select("kubeConfig")
	for i := len(opts) - 1; i >= 0; i-- {
		// `alias` optional argument
		if !querybuilder.IsZeroValue(opts[i].Alias) {
			q = q.Arg("alias", opts[i].Alias)
		}
	}

	return &File{
		query: q,
	}
}

func (r *Query) Kwok() *Kwok { // kwok (../../../:0:0)
	q := r.query.Select("kwok")

	return &Kwok{
		query: q,
	}
}
