// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Gh struct { // gh (../../../gh/main.go:10:6)
	query *querybuilder.Selection

	id          *ID
	setSecret   *Void
	setVariable *Void
}

func (r *Gh) WithGraphQLQuery(q *querybuilder.Selection) *Gh {
	return &Gh{
		query: q,
	}
}

func (r *Gh) Container() *Container { // gh (../../../gh/main.go:11:2)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// A unique identifier for this Gh.
func (r *Gh) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Gh) XXX_GraphQLType() string {
	return "Gh"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Gh) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Gh) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Gh) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Gh) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Gh{query: selectNode(dag.query, id, "Gh")}
	return nil
}

func (r *Gh) Release(repo string, tag string) *GhRelease { // gh (../../../gh/main.go:39:1)
	q := r.query.Select("release")
	q = q.Arg("repo", repo)
	q = q.Arg("tag", tag)

	return &GhRelease{
		query: q,
	}
}

// GhSetSecretOpts contains options for Gh.SetSecret
type GhSetSecretOpts struct {
	App string // gh (../../../gh/main.go:182:2)

	Env string // gh (../../../gh/main.go:184:2)

	Org string // gh (../../../gh/main.go:186:2)

	Visibility string // gh (../../../gh/main.go:188:2)

	User bool // gh (../../../gh/main.go:190:2)

	NoReposSelected bool // gh (../../../gh/main.go:192:2)

	Repo []string // gh (../../../gh/main.go:194:2)
}

func (r *Gh) SetSecret(ctx context.Context, name string, body *Secret, opts ...GhSetSecretOpts) error { // gh (../../../gh/main.go:177:1)
	assertNotNil("body", body)
	if r.setSecret != nil {
		return nil
	}
	q := r.query.Select("setSecret")
	for i := len(opts) - 1; i >= 0; i-- {
		// `app` optional argument
		if !querybuilder.IsZeroValue(opts[i].App) {
			q = q.Arg("app", opts[i].App)
		}
		// `env` optional argument
		if !querybuilder.IsZeroValue(opts[i].Env) {
			q = q.Arg("env", opts[i].Env)
		}
		// `org` optional argument
		if !querybuilder.IsZeroValue(opts[i].Org) {
			q = q.Arg("org", opts[i].Org)
		}
		// `visibility` optional argument
		if !querybuilder.IsZeroValue(opts[i].Visibility) {
			q = q.Arg("visibility", opts[i].Visibility)
		}
		// `user` optional argument
		if !querybuilder.IsZeroValue(opts[i].User) {
			q = q.Arg("user", opts[i].User)
		}
		// `noReposSelected` optional argument
		if !querybuilder.IsZeroValue(opts[i].NoReposSelected) {
			q = q.Arg("noReposSelected", opts[i].NoReposSelected)
		}
		// `repo` optional argument
		if !querybuilder.IsZeroValue(opts[i].Repo) {
			q = q.Arg("repo", opts[i].Repo)
		}
	}
	q = q.Arg("name", name)
	q = q.Arg("body", body)

	return q.Execute(ctx)
}

// GhSetVariableOpts contains options for Gh.SetVariable
type GhSetVariableOpts struct {
	Env string // gh (../../../gh/main.go:204:2)

	Org string // gh (../../../gh/main.go:206:2)

	Visibility string // gh (../../../gh/main.go:208:2)

	Repo []string // gh (../../../gh/main.go:210:2)
}

func (r *Gh) SetVariable(ctx context.Context, name string, body *Secret, opts ...GhSetVariableOpts) error { // gh (../../../gh/main.go:199:1)
	assertNotNil("body", body)
	if r.setVariable != nil {
		return nil
	}
	q := r.query.Select("setVariable")
	for i := len(opts) - 1; i >= 0; i-- {
		// `env` optional argument
		if !querybuilder.IsZeroValue(opts[i].Env) {
			q = q.Arg("env", opts[i].Env)
		}
		// `org` optional argument
		if !querybuilder.IsZeroValue(opts[i].Org) {
			q = q.Arg("org", opts[i].Org)
		}
		// `visibility` optional argument
		if !querybuilder.IsZeroValue(opts[i].Visibility) {
			q = q.Arg("visibility", opts[i].Visibility)
		}
		// `repo` optional argument
		if !querybuilder.IsZeroValue(opts[i].Repo) {
			q = q.Arg("repo", opts[i].Repo)
		}
	}
	q = q.Arg("name", name)
	q = q.Arg("body", body)

	return q.Execute(ctx)
}

// AsNode returns this Gh as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Gh) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

type GhRelease struct { // gh (../../../gh/main.go:30:6)
	query *querybuilder.Selection

	create *Void
	edit   *Void
	id     *ID
	upload *Void
}

func (r *GhRelease) WithGraphQLQuery(q *querybuilder.Selection) *GhRelease {
	return &GhRelease{
		query: q,
	}
}

// GhReleaseCreateOpts contains options for GhRelease.Create
type GhReleaseCreateOpts struct {
	Title string // gh (../../../gh/main.go:46:2)

	GenerateNotes bool // gh (../../../gh/main.go:48:2)

	Latest bool // gh (../../../gh/main.go:50:2)

	Prerelease bool // gh (../../../gh/main.go:52:2)

	Draft bool // gh (../../../gh/main.go:54:2)

	VerifyTag bool // gh (../../../gh/main.go:56:2)
}

func (r *GhRelease) Create(ctx context.Context, opts ...GhReleaseCreateOpts) error { // gh (../../../gh/main.go:43:1)
	if r.create != nil {
		return nil
	}
	q := r.query.Select("create")
	for i := len(opts) - 1; i >= 0; i-- {
		// `title` optional argument
		if !querybuilder.IsZeroValue(opts[i].Title) {
			q = q.Arg("title", opts[i].Title)
		}
		// `generateNotes` optional argument
		if !querybuilder.IsZeroValue(opts[i].GenerateNotes) {
			q = q.Arg("generateNotes", opts[i].GenerateNotes)
		}
		// `latest` optional argument
		if !querybuilder.IsZeroValue(opts[i].Latest) {
			q = q.Arg("latest", opts[i].Latest)
		}
		// `prerelease` optional argument
		if !querybuilder.IsZeroValue(opts[i].Prerelease) {
			q = q.Arg("prerelease", opts[i].Prerelease)
		}
		// `draft` optional argument
		if !querybuilder.IsZeroValue(opts[i].Draft) {
			q = q.Arg("draft", opts[i].Draft)
		}
		// `verifyTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].VerifyTag) {
			q = q.Arg("verifyTag", opts[i].VerifyTag)
		}
	}

	return q.Execute(ctx)
}

// GhReleaseEditOpts contains options for GhRelease.Edit
type GhReleaseEditOpts struct {
	Title string // gh (../../../gh/main.go:90:2)

	GenerateNotes bool // gh (../../../gh/main.go:92:2)

	Latest bool // gh (../../../gh/main.go:94:2)

	Prerelease bool // gh (../../../gh/main.go:96:2)

	Draft bool // gh (../../../gh/main.go:98:2)

	VerifyTag bool // gh (../../../gh/main.go:100:2)
}

func (r *GhRelease) Edit(ctx context.Context, opts ...GhReleaseEditOpts) error { // gh (../../../gh/main.go:87:1)
	if r.edit != nil {
		return nil
	}
	q := r.query.Select("edit")
	for i := len(opts) - 1; i >= 0; i-- {
		// `title` optional argument
		if !querybuilder.IsZeroValue(opts[i].Title) {
			q = q.Arg("title", opts[i].Title)
		}
		// `generateNotes` optional argument
		if !querybuilder.IsZeroValue(opts[i].GenerateNotes) {
			q = q.Arg("generateNotes", opts[i].GenerateNotes)
		}
		// `latest` optional argument
		if !querybuilder.IsZeroValue(opts[i].Latest) {
			q = q.Arg("latest", opts[i].Latest)
		}
		// `prerelease` optional argument
		if !querybuilder.IsZeroValue(opts[i].Prerelease) {
			q = q.Arg("prerelease", opts[i].Prerelease)
		}
		// `draft` optional argument
		if !querybuilder.IsZeroValue(opts[i].Draft) {
			q = q.Arg("draft", opts[i].Draft)
		}
		// `verifyTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].VerifyTag) {
			q = q.Arg("verifyTag", opts[i].VerifyTag)
		}
	}

	return q.Execute(ctx)
}

// A unique identifier for this GhRelease.
func (r *GhRelease) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *GhRelease) XXX_GraphQLType() string {
	return "GhRelease"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *GhRelease) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *GhRelease) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *GhRelease) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *GhRelease) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = GhRelease{query: selectNode(dag.query, id, "GhRelease")}
	return nil
}

// GhReleaseUploadOpts contains options for GhRelease.Upload
type GhReleaseUploadOpts struct {
	Clobber bool // gh (../../../gh/main.go:135:2)
}

func (r *GhRelease) Upload(ctx context.Context, assets []*File, opts ...GhReleaseUploadOpts) error { // gh (../../../gh/main.go:131:1)
	if r.upload != nil {
		return nil
	}
	q := r.query.Select("upload")
	for i := len(opts) - 1; i >= 0; i-- {
		// `clobber` optional argument
		if !querybuilder.IsZeroValue(opts[i].Clobber) {
			q = q.Arg("clobber", opts[i].Clobber)
		}
	}
	q = q.Arg("assets", assets)

	return q.Execute(ctx)
}

// AsNode returns this GhRelease as a Node.
// This is a local type conversion — no GraphQL call.
func (r *GhRelease) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// GhOpts contains options for Query.Gh
type GhOpts struct {
	Container *Container // gh (../../../gh/main.go:17:2)
}

func (r *Query) Gh(githubToken *Secret, opts ...GhOpts) *Gh { // gh (../../../gh/main.go:14:1)
	assertNotNil("githubToken", githubToken)
	q := r.query.Select("gh")
	for i := len(opts) - 1; i >= 0; i-- {
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}
	q = q.Arg("githubToken", githubToken)

	return &Gh{
		query: q,
	}
}
