// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

func (r *Query) Release(src *GitRef) *Release { // release (../../../:0:0)
	assertNotNil("src", src)
	q := r.query.Select("release")
	q = q.Arg("src", src)

	return &Release{
		query: q,
	}
}

type Release struct { // release (../../../:0:0)
	query *querybuilder.Selection

	create *Void
	id     *ID
}

func (r *Release) WithGraphQLQuery(q *querybuilder.Selection) *Release {
	return &Release{
		query: q,
	}
}

// ReleaseCreateOpts contains options for Release.Create
type ReleaseCreateOpts struct {
	Cgo bool

	// Default: ["linux","darwin"]
	Goos []string

	// Default: ["amd64","arm64"]
	Goarch []string

	Brew bool
}

func (r *Release) Create(ctx context.Context, githubToken *Secret, githubRepo string, name string, opts ...ReleaseCreateOpts) error {
	assertNotNil("githubToken", githubToken)
	if r.create != nil {
		return nil
	}
	q := r.query.Select("create")
	for i := len(opts) - 1; i >= 0; i-- {
		// `cgo` optional argument
		if !querybuilder.IsZeroValue(opts[i].Cgo) {
			q = q.Arg("cgo", opts[i].Cgo)
		}
		// `goos` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goos) {
			q = q.Arg("goos", opts[i].Goos)
		}
		// `goarch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goarch) {
			q = q.Arg("goarch", opts[i].Goarch)
		}
		// `brew` optional argument
		if !querybuilder.IsZeroValue(opts[i].Brew) {
			q = q.Arg("brew", opts[i].Brew)
		}
	}
	q = q.Arg("githubToken", githubToken)
	q = q.Arg("githubRepo", githubRepo)
	q = q.Arg("name", name)

	return q.Execute(ctx)
}

// A unique identifier for this Release.
func (r *Release) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Release) XXX_GraphQLType() string {
	return "Release"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Release) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Release) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Release) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Release) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Release{query: selectNode(dag.query, id, "Release")}
	return nil
}
